# Generated by Django 2.0.2 on 2018-06-28 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ccd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('exists', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='amur-ccd-west', max_length=13)),
                ('tube', models.CharField(default='west', max_length=4)),
                ('last_imobj', models.CharField(default='-', max_length=8)),
                ('last_imobj_stclass', models.CharField(default='table-info', max_length=13)),
                ('last_imtime', models.CharField(default='-', max_length=19)),
                ('last_imtime_stclass', models.CharField(default='table-info', max_length=13)),
                ('zi_mstat_val', models.CharField(max_length=7)),
                ('zi_mstat_ts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Ebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('exists', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='main-server', max_length=35)),
                ('ipaddr', models.GenericIPAddressField(default='127.0.0.1')),
                ('zi_pingval', models.SmallIntegerField(default=0)),
                ('zi_pingts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Focuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('exists', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='amur-ccd-west', max_length=13)),
                ('tube', models.CharField(default='west', max_length=4)),
                ('zi_fpval', models.CharField(max_length=7)),
                ('zi_fpts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='amur-head', max_length=12)),
                ('zitem_task_val', models.CharField(max_length=7)),
                ('zitem_task_ts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MainServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='main-server', max_length=35)),
                ('ipaddr', models.GenericIPAddressField(default='127.0.0.1')),
                ('zi_pingval', models.SmallIntegerField(default=0)),
                ('zi_pingts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sitename', models.CharField(max_length=14)),
                ('lat', models.CharField(blank=True, max_length=12, null=True)),
                ('lon', models.CharField(blank=True, max_length=12, null=True)),
                ('elev', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('website', models.URLField(blank=True, max_length=30, null=True)),
                ('m2dburl', models.URLField(blank=True, max_length=30, null=True)),
                ('sun_alt', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('sun_alt_stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='amur-mount', max_length=12)),
                ('zi_mstat_val', models.CharField(max_length=7)),
                ('zi_mstat_ts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='SecondServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=14)),
                ('exists', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('zbsrv', models.CharField(default='MASTER-Zabbix-Server-3', max_length=22)),
                ('hostid', models.IntegerField(default=99999)),
                ('hostname', models.CharField(default='main-server', max_length=35)),
                ('ipaddr', models.GenericIPAddressField(default='127.0.0.1')),
                ('zi_pingval', models.SmallIntegerField(default=0)),
                ('zi_pingts', models.IntegerField(default=1519398497)),
                ('status', models.CharField(default='OK', max_length=7)),
                ('stclass', models.CharField(default='table-info', max_length=13)),
            ],
        ),
    ]
