# Generated by Django 2.0.2 on 2018-02-22 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sitename', models.CharField(max_length=20)),
                ('status', models.CharField(default='OK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sitename', models.CharField(max_length=20)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lon', models.CharField(blank=True, max_length=20, null=True)),
                ('elev', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
